kind: Deployment
apiVersion: apps/v1
metadata:
  name: api
  namespace: mongo
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
           - name: FACEPLUSPLUS_API_KEY
             valueFrom:
               secretKeyRef:
                 name: faceplusplus-creds
                 key: FACEPLUSPLUS_API_KEY
           - name: FACEPLUSPLUS_API_SECRET
             valueFrom:
               secretKeyRef:
                 name: faceplusplus-creds
                 key: FACEPLUSPLUS_API_SECRET
           - name: RapidAPI_KEY
             valueFrom:
               secretKeyRef:
                 name: rapidapi-creds
                 key: RapidAPI_KEY
           - name: MONGO_CLIENT
             value: "10.104.110.188:27017"
           - name: MONGO_DATABASE
             value: demo
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: mongo
  labels:
    name: api-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: api
  type: LoadBalancer